### ISSUE TITLE
List to dict formatting

### ISSUE THREAD

**Issue by kaizer1v** [DataKind-BLR/QuestAlliance#1]
[This function](https://github.com/DataKind-BLR/QuestAlliance/blob/eab4cf33e46e462cb6e9e7f6482712cc11857f3b/aasaan_jobs/aasaanjobs.py#L94) produces a result **like** the following

The list
```python
['key1', 'value1', 'key2', 'value2.1', 'value2.2', 'key3', 'value3']
```
currently maps to a dictionary like

```python
{
  'key1': 'value1',
  'key2': 'value2.1',
  'value2.2': 'key3',
  'value3': NULL
}
```

whereas the expected result should be
```python
{
  'key1': ['value1'],
  'key2': ['value2.1', 'value2.2'],
  'key3': ['value3']
}
```

**Comment by nirmalsinghania2008** [comment]
```
key_list = ['key1', 'value1', 'key2','value2.1', 'value2.2','key3','value3']
hashmap = {}
curr_key = ""
for val in key_list:
    if 'key' in val:
        curr_key = val
        hashmap[val] = []
    else:
        hashmap[curr_key].append(val)
        
        
        
    
```

**Comment by raghuramdr** [comment]
@nirmalsinghania2008 I think he is referring to a more generic example. I will try to work on this tonight. If not, I will start on it tomorrow morning. @kaizer1v will let you now when I start on this.

**Comment by kaizer1v** [comment]
This issue has been resolved.
