### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by raghuramdr** [DataKind-BLR/QuestAlliance#6]
DEBUG:urllib3.connectionpool:https://www.aasaanjobs.com:443 "GET /job/field-sales-executive-hyderabad-ad7990-in-ninjacart/e37dacde-6c00-494c-9f01-e48ebafb952f/ HTTP/1.1" 200 None
DEBUG:kirmi:Request time elapsed : 0.516427
```
Traceback (most recent call last):
  File "aasaanjobs.py", line 137, in <module>
    run_process()
  File "aasaanjobs.py", line 133, in run_process
    process_job_url(jobs, job_category, number_of_pages)
  File "aasaanjobs.py", line 108, in process_job_url
    get_job_details(job_url)
  File "aasaanjobs.py", line 50, in get_job_details
    job_details['salary_max'] = soup.find_all('span', attrs={'itemprop': 'maxValue'})[0].text

IndexError: list index out of range
```

**Comment by raghuramdr** [comment]
@kaizer1v Did you encounter this bug? If no one is able to reproduce this, we will have to close it.

**Comment by raghuramdr** [comment]
@DataKind-BLR/quest_alliance Can anyone reproduce this bug? If not, will close this issue. Looks more like a network issue/

**Comment by yashodhan19** [comment]
Missing Value on the Page, This issue is taken care of, the URL will be added to the error list
